apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: nedemenang/udagram-api-user
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m" 
        env:
        - name: POSTGRES_HOST
          valueFrom:
            configMapKeyRef:
              name: env-variables
              key: POSTGRES_HOST
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: env-variables
              key: POSTGRES_DB
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_USERNAME
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secret
              key: POSTGRES_PASSWORD
        - name: JWT_SECRET
          valueFrom:
            configMapKeyRef:
              name: env-variables
              key: JWT_SECRET
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: env-variables
              key: URL
        - name: AWS_PROFILE
          valueFrom:
            configMapKeyRef:
              name: env-variables
              key: AWS_PROFILE
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: env-variables
              key: AWS_REGION
        - name: AWS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: env-variables
              key: AWS_BUCKET
        volumeMounts:
        - name: aws-secret
          mountPath: "/root/.aws/"
          readOnly: true
      restartPolicy: Always
      volumes:
      - name: aws-secret
        secret:
          secretName: aws-secret